#!/usr/bin/env python3
"""
figures.py — figure rendering for the ETCG manuscript.

Driven entirely by the matrices and registry that analysis.py computes, so a figure cannot
disagree with the table beside it. This is not a standalone entry point; run analysis.py.

Round 1 note: the submitted Figure 2 showed two conditions under a caption promising three,
because the figure PDFs in the manuscript tree predated the Intermediate condition. Figures
are now regenerated by the same run that produces the numbers, into both trees at once.
"""

from __future__ import annotations

from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.patches as mpatches
import matplotlib.pyplot as plt
import numpy as np

CONDITIONS = ["etcg", "intermediate", "baseline"]
CONDITION_LABELS = {"etcg": "ETCG", "intermediate": "Intermediate", "baseline": "Baseline"}
DIMENSIONS = ["specificity", "testability", "risk_coverage", "clarity", "actionability"]
DIMENSION_LABELS = ["Specificity", "Testability", "Risk\nCoverage", "Clarity", "Actionability"]

# Print-safe, colour-blind-distinguishable, and legible in greyscale.
COLORS = {"etcg": "#0571B0", "intermediate": "#4DAC26", "baseline": "#CA0020"}

plt.rcParams.update({
    "font.family": "serif",
    "font.serif": ["Times New Roman", "DejaVu Serif"],
    "font.size": 10,
    "axes.labelsize": 10,
    "axes.titlesize": 10,
    "xtick.labelsize": 9,
    "ytick.labelsize": 9,
    "legend.fontsize": 9,
    "figure.dpi": 200,
    "savefig.bbox": "tight",
    "savefig.pad_inches": 0.02,
    "pdf.fonttype": 42,
})


def _save(fig, name: str, out_dirs: list[Path]) -> list[Path]:
    written = []
    for d in out_dirs:
        d.mkdir(parents=True, exist_ok=True)
        path = d / name
        fig.savefig(path, format="pdf")
        written.append(path)
    plt.close(fig)
    return written


def make_paired_boxplot(matrices: dict, reg, out_dirs: list[Path]) -> list[Path]:
    """Specification-level distributions with the pairing made visible.

    Each grey line connects the same specification across conditions. The paired structure
    is the reason the analysis uses signed-rank rather than rank-sum tests, so the figure
    shows it rather than hiding it behind marginal distributions.
    """
    fig, ax = plt.subplots(figsize=(6.0, 4.0))
    data = [matrices["spec_pct"][c] for c in CONDITIONS]
    positions = np.arange(1, len(CONDITIONS) + 1)

    # One jitter offset per specification, shared by its point in every condition and by
    # the line connecting them, so a line visibly joins the dots it belongs to.
    rng = np.random.default_rng(42)  # presentation only; affects no reported value
    n_specs = len(matrices["specs"])
    jitter = rng.uniform(-0.13, 0.13, size=n_specs)

    for i in range(n_specs):
        ax.plot(positions + jitter[i], [d[i] for d in data], color="#9A9A9A",
                linewidth=0.5, alpha=0.45, zorder=1, solid_capstyle="round")

    bp = ax.boxplot(data, positions=positions, widths=0.62, patch_artist=True,
                    showfliers=False, zorder=2,
                    medianprops={"color": "#222222", "linewidth": 1.4},
                    whiskerprops={"color": "#555555"}, capprops={"color": "#555555"},
                    boxprops={"linewidth": 1.0})
    for patch, cond in zip(bp["boxes"], CONDITIONS):
        patch.set_facecolor(COLORS[cond])
        patch.set_alpha(0.18)
        patch.set_edgecolor(COLORS[cond])

    for pos, cond, vals in zip(positions, CONDITIONS, data):
        ax.scatter(pos + jitter, vals, s=15, color=COLORS[cond], alpha=0.85,
                   edgecolors="white", linewidths=0.4, zorder=3)
        ax.scatter([pos], [vals.mean()], marker="D", s=46, color=COLORS[cond],
                   edgecolors="black", linewidths=0.8, zorder=5)

    ax.set_xticks(positions)
    ax.set_xticklabels([CONDITION_LABELS[c] for c in CONDITIONS])
    ax.set_ylabel("Charter quality (\\%)" if plt.rcParams["text.usetex"]
                  else "Charter quality (%)")
    ax.set_ylim(bottom=min(min(d) for d in data) - 3, top=101.5)
    ax.grid(axis="y", linestyle=":", linewidth=0.6, color="#CCCCCC", zorder=0)
    ax.set_axisbelow(True)
    for spine in ("top", "right"):
        ax.spines[spine].set_visible(False)

    handles = [mpatches.Patch(facecolor=COLORS[c], alpha=0.35, edgecolor=COLORS[c],
                              label=CONDITION_LABELS[c]) for c in CONDITIONS]
    handles.append(plt.Line2D([], [], color="#B0B0B0", linewidth=0.9,
                              label="Same specification"))
    handles.append(plt.Line2D([], [], marker="D", color="none", markerfacecolor="#666666",
                              markeredgecolor="black", markersize=6, label="Condition mean"))
    ax.legend(handles=handles, loc="lower left", frameon=False, ncol=2, fontsize=8)

    return _save(fig, "figure-02-boxplot.pdf", out_dirs)


def make_radar(matrices: dict, reg, out_dirs: list[Path]) -> list[Path]:
    """Five-dimension quality profile for all three conditions."""
    means = {c: [matrices["spec_dim"][c][d].mean() for d in DIMENSIONS] for c in CONDITIONS}

    angles = np.linspace(0, 2 * np.pi, len(DIMENSIONS), endpoint=False).tolist()
    angles += angles[:1]

    fig, ax = plt.subplots(figsize=(4.6, 4.6), subplot_kw={"projection": "polar"})
    ax.set_theta_offset(np.pi / 2)
    ax.set_theta_direction(-1)
    ax.set_xticks(angles[:-1])
    ax.set_xticklabels(DIMENSION_LABELS, fontsize=9)
    ax.set_ylim(2.4, 3.02)
    ax.set_yticks([2.5, 2.7, 2.9])
    ax.set_yticklabels(["2.5", "2.7", "2.9"], fontsize=7.5, color="grey")
    ax.grid(color="#D5D5D5", linewidth=0.6)
    ax.spines["polar"].set_color("#CCCCCC")

    styles = {"etcg": "-", "intermediate": "--", "baseline": "-."}
    markers = {"etcg": "o", "intermediate": "^", "baseline": "s"}
    for cond in CONDITIONS:
        vals = means[cond] + means[cond][:1]
        ax.plot(angles, vals, color=COLORS[cond], linewidth=1.8,
                linestyle=styles[cond], zorder=3)
        ax.fill(angles, vals, color=COLORS[cond], alpha=0.10, zorder=2)
        ax.plot(angles[:-1], means[cond], markers[cond], color=COLORS[cond],
                markersize=4.5, zorder=4)

    handles = [plt.Line2D([], [], color=COLORS[c], linestyle=styles[c], marker=markers[c],
                          markersize=5, linewidth=1.8, label=CONDITION_LABELS[c])
               for c in CONDITIONS]
    ax.legend(handles=handles, loc="upper right", bbox_to_anchor=(1.22, 1.13),
              frameon=False, fontsize=8.5)

    return _save(fig, "figure-03-radar.pdf", out_dirs)


def make_richness_barchart(matrices: dict, reg, out_dirs: list[Path]) -> list[Path]:
    """Mean quality by specification richness group, with the group n made explicit.

    Error bars are 95% confidence intervals rather than +/-1 SD: the structured group holds
    seven specifications, and a CI shows that uncertainty where an SD bar understates it.
    """
    from analysis import SPARSE_SPECS, STRUCTURED_SPECS, ci_mean

    specs = matrices["specs"]
    groups = {
        "Sparse": [i for i, s in enumerate(specs) if s in SPARSE_SPECS],
        "Structured": [i for i, s in enumerate(specs) if s in STRUCTURED_SPECS],
    }

    fig, ax = plt.subplots(figsize=(6.0, 3.8))
    width = 0.26
    xs = np.arange(len(groups))

    for k, cond in enumerate(CONDITIONS):
        means, errs = [], [[], []]
        for idxs in groups.values():
            vals = matrices["spec_pct"][cond][idxs]
            m = float(vals.mean())
            lo, hi = ci_mean(vals)
            means.append(m)
            errs[0].append(max(0.0, m - lo))
            errs[1].append(max(0.0, hi - m))
        offset = (k - 1) * width
        bars = ax.bar(xs + offset, means, width, label=CONDITION_LABELS[cond],
                      color=COLORS[cond], alpha=0.85, edgecolor="white", linewidth=0.8,
                      zorder=3)
        ax.errorbar(xs + offset, means, yerr=errs, fmt="none", ecolor="#333333",
                    elinewidth=0.9, capsize=3, zorder=4)
        for bar, m in zip(bars, means):
            ax.text(bar.get_x() + bar.get_width() / 2, 78.5, f"{m:.1f}",
                    ha="center", va="bottom", fontsize=7.5, color="white", zorder=5)

    ax.set_xticks(xs)
    ax.set_xticklabels([f"{name}\n(n = {len(idxs)} specifications)"
                        for name, idxs in groups.items()])
    ax.set_ylabel("Mean charter quality (%)")
    ax.set_ylim(75, 104)
    ax.grid(axis="y", linestyle=":", linewidth=0.6, color="#CCCCCC", zorder=0)
    ax.set_axisbelow(True)
    for spine in ("top", "right"):
        ax.spines[spine].set_visible(False)
    ax.legend(frameon=False, ncol=3, loc="upper left", fontsize=8.5)

    return _save(fig, "figure-04-barchart.pdf", out_dirs)


def render_all(matrices: dict, reg, *out_dirs: Path) -> list[Path]:
    dirs = [Path(d) for d in out_dirs]
    written = []
    written += make_paired_boxplot(matrices, reg, dirs)
    written += make_radar(matrices, reg, dirs)
    written += make_richness_barchart(matrices, reg, dirs)
    return written
